### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by tuturkiener** [azerpas/nike_Raffle_FR#1]
How do we harvest captcha responses?

**Comment by ymmxl** [comment]
i believe its to be implemented with the captcha harvester created by him.

**Comment by azerpas** [comment]
Yeah, please check my captcha harvester repository, it’s multi-threaded

**Comment by ymmxl** [comment]
Hey there,
I was wondering if you would help me out by tweaking it to work on
Offspring UK.

Been dealing with that and the captcha harvester in a while now. Thanks and
regards.

**Comment by ec0shi** [comment]
[
<img width="460" alt="screen shot 2017-10-29 at 9 03 45 pm" src="https://user-images.githubusercontent.com/32888626/32150701-b28f7dbc-bcec-11e7-826a-e30a05bd72c9.png">
](url)

Hello, I got this error.

Can you please tell me how to solve?

**Comment by ec0shi** [comment]
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    ra = Raffle()
TypeError: __init__() takes exactly 3 arguments (1 given)


Hello, I got this error.

Can you tell me how to solve?
