### ISSUE TITLE
Shoe ID

### ISSUE THREAD

**Issue by ymmxl** [azerpas/nike_Raffle_FR#3]
Hey there, is the shoe id '8' as found in the page source? this is for the nike air max 90

`<input class="hidden-input" type="text" data-parsley-trigger="change" readonly value="8" name="shoe_id" required="" />`

**Comment by ymmxl** [comment]
also need some guidance on the `siteid`. Million thanks.

**Comment by ymmxl** [comment]
Thanks man i found it. My bad.

**Comment by azerpas** [comment]
Yup, site id, shoes id, etc are part of requests made to website
