### ISSUE TITLE
Captcha not called to the g-recaptcha-response

### ISSUE THREAD

**Issue by ymmxl** [azerpas/nike_Raffle_FR#4]
Hey there, i'm using python 3 to run this script. 
When pickle calls the random choice of available captchas, it doesnt get called to the g-recaptcha-response.
Can you take a look at the code please? thanks

**Comment by azerpas** [comment]
Hey, I don't get what you mean? Working good for me

**Comment by azerpas** [comment]
Try Selenium version if you can't get requests version working, it's easier

**Comment by ymmxl** [comment]
its fine, after hours and hours i finally got it to work.
Can i DM you for some questions?

**Comment by azerpas** [comment]
of course man
